import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("desktop shell exposes Jarvis wake-word UI and safe preload boundary", () => {
  const html = readFileSync("src/desktop/index.html", "utf-8");
  const renderer = readFileSync("src/desktop/renderer.js", "utf-8");
  const main = readFileSync("src/desktop/main.cjs", "utf-8");
  const preload = readFileSync("src/desktop/preload.cjs", "utf-8");

  assert.match(html, /Arcigy Jarvis/);
  assert.match(html, /Enable/);
  assert.match(html, /Contract generator/);
  assert.match(html, /contractIntake/);
  assert.match(html, /healthGrid/);
  assert.match(html, /draftReply/);
  assert.match(html, /Client memory/);
  assert.match(html, /memoryEmail/);
  assert.match(html, /identifyEmail/);
  assert.match(html, /ingestClientMessage/);
  assert.match(html, /Operations sync/);
  assert.match(html, /gmailQuery/);
  assert.match(html, /syncGmail/);
  assert.match(html, /smartleadCampaignId/);
  assert.match(html, /checkSmartlead/);
  assert.match(html, /Lead discovery/);
  assert.match(html, /leadQuery/);
  assert.match(html, /discoverLeads/);
  assert.match(html, /exportLeads/);
  assert.match(renderer, /SpeechRecognition/);
  assert.match(renderer, /speechSynthesis/);
  assert.match(renderer, /window\.arcigyDesktop/);
  assert.match(renderer, /arcigyApi\.jarvisVoiceEvent/);
  assert.match(renderer, /arcigyApi\.coldOutreachBrief/);
  assert.match(renderer, /arcigyApi\.identifyEmail/);
  assert.match(renderer, /arcigyApi\.ingestClientMessage/);
  assert.match(renderer, /arcigyApi\.generateContracts/);
  assert.match(renderer, /arcigyApi\.systemHealth/);
  assert.match(renderer, /arcigyApi\.generateAiReply/);
  assert.match(renderer, /arcigyApi\.syncGmailRecentMessages/);
  assert.match(renderer, /arcigyApi\.getSmartleadCampaignStatus/);
  assert.match(renderer, /arcigyApi\.discoverLeads/);
  assert.match(renderer, /arcigyApi\.appendLeadsToGoogleSheet/);
  assert.match(renderer, /\/api\/system-health/);
  assert.match(renderer, /\/api\/identify-email/);
  assert.match(renderer, /\/api\/ingest-client-message/);
  assert.match(renderer, /\/api\/sync-gmail-recent-messages/);
  assert.match(renderer, /\/api\/smartlead-campaign-status/);
  assert.match(renderer, /\/api\/discover-leads/);
  assert.match(renderer, /\/api\/append-leads-to-google-sheet/);
  assert.match(renderer, /sampleContractIntake/);
  assert.doesNotMatch(renderer, /demoColdOutreachMetrics/);
  assert.doesNotMatch(renderer, /Za dnes sme napísali/);
  assert.match(main, /ipcMain\.handle\("jarvis:coldOutreachBrief"/);
  assert.match(main, /ipcMain\.handle\("jarvis:identifyEmail"/);
  assert.match(main, /ipcMain\.handle\("jarvis:ingestClientMessage"/);
  assert.match(main, /ipcMain\.handle\("jarvis:voiceEvent"/);
  assert.match(main, /summarizeHealthForVoice/);
  assert.match(main, /summarizeIdentityForVoice/);
  assert.match(main, /summarizeLeadsForVoice/);
  assert.match(main, /cleanVoiceQuery/);
  assert.match(main, /ipcMain\.handle\("jarvis:systemHealth"/);
  assert.match(main, /ipcMain\.handle\("jarvis:generateAiReply"/);
  assert.match(main, /ipcMain\.handle\("jarvis:syncGmailRecentMessages"/);
  assert.match(main, /ipcMain\.handle\("jarvis:getSmartleadCampaignStatus"/);
  assert.match(main, /ipcMain\.handle\("jarvis:discoverLeads"/);
  assert.match(main, /ipcMain\.handle\("jarvis:appendLeadsToGoogleSheet"/);
  assert.match(main, /listRecentGmailMessageEvents/);
  assert.match(main, /getSmartleadCampaignStatus/);
  assert.match(main, /searchGooglePlacesLeads/);
  assert.match(main, /getSerperApiKeys/);
  assert.match(main, /ipcMain\.handle\("contracts:generate"/);
  assert.match(main, /jarvis_local_db\.py/);
  assert.match(main, /cold-brief/);
  assert.match(main, /defaultDbPath/);
  assert.match(main, /contextIsolation: true/);
  assert.match(main, /nodeIntegration: false/);
  assert.match(preload, /contextBridge\.exposeInMainWorld/);
  assert.match(preload, /jarvisVoiceEvent/);
  assert.match(preload, /coldOutreachBrief/);
  assert.match(preload, /identifyEmail/);
  assert.match(preload, /ingestClientMessage/);
  assert.match(preload, /systemHealth/);
  assert.match(preload, /generateAiReply/);
  assert.match(preload, /syncGmailRecentMessages/);
  assert.match(preload, /getSmartleadCampaignStatus/);
  assert.match(preload, /discoverLeads/);
  assert.match(preload, /appendLeadsToGoogleSheet/);
  assert.match(preload, /generateContracts/);
});
