import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("web tunnel script orchestrates protected Jarvis MCP exposure", () => {
  const packageJson = JSON.parse(readFileSync("package.json", "utf-8")) as { scripts: Record<string, string> };
  const script = readFileSync("scripts/start_web_tunnel.ts", "utf-8");

  assert.equal(packageJson.scripts["web:tunnel"], "node scripts/start_web_tunnel.ts");
  assert.equal(packageJson.scripts["web:tunnel:secure"], "node scripts/start_web_tunnel.ts --generate-token");
  assert.match(script, /JARVIS_WEB_TOKEN/);
  assert.match(script, /randomBytes/);
  assert.match(script, /src\/server\/local-api-server\.ts/);
  assert.match(script, /\/api\/web-bridge-preflight/);
  assert.match(script, /fetchJson<Preflight>\(`\$\{origin\}\/api\/web-bridge-preflight`, token\)/);
  assert.match(script, /headers\.authorization = `Bearer \$\{token\}`/);
  assert.match(script, /\/\.well-known\/arcigy-jarvis\.json/);
  assert.match(script, /External connection pack/);
  assert.match(script, /includeReadiness=true&live=true/);
  assert.match(script, /\/api\/remote-mcp-smoke/);
  assert.match(script, /verifyExternalConnectionPack/);
  assert.match(script, /hasGuardedConnectionPackLimits/);
  assert.match(script, /hasAgentSetupProfiles/);
  assert.match(script, /agentSetupProfiles/);
  assert.match(script, /structured Claude, ChatGPT, Grok, and generic HTTP agent setup profiles/);
  assert.match(script, /profile\?\.firstTool === "arcigy\.get_operator_briefing"/);
  assert.match(script, /profile\?\.writePolicy === "approval\.approved-required"/);
  assert.match(script, /profile\?\.localWritePolicy === "dry-run-first"/);
  assert.match(script, /requiredAgentSetupProofGates/);
  assert.match(script, /requiredAgentSetupProofGates\.every\(\(gate\) => gates\.includes\(gate\)\)/);
  assert.match(script, /pathPolicy === "repo-only"/);
  assert.match(script, /writesRequireExplicitToolCall === true/);
  assert.match(script, /bounded JSON/);
  assert.match(script, /body\.auth\?\.header !== "Authorization: Bearer <JARVIS_WEB_TOKEN>"/);
  assert.match(script, /body\.mcpToolCallPattern !== `\$\{publicUrl\}\/api\/mcp\/\{toolName\}`/);
  assert.match(script, /body\.handoff\?\.connectionPackUrl !== `\$\{publicUrl\}\/api\/remote-mcp-pack\?includeReadiness=true&live=true`/);
  assert.match(script, /verifyRemoteMcpSmoke/);
  assert.match(script, /hasReadySmokeCheck/);
  assert.match(script, /manifest-tool-registry/);
  assert.match(script, /manifest-tool-metadata/);
  assert.match(script, /pack-tool-registry/);
  assert.match(script, /pack-quick-start-approval-policy/);
  assert.match(script, /pack-handoff-proof/);
  assert.match(script, /pack-agent-compatibility/);
  assert.match(script, /pack-client-memory-quick-start/);
  assert.match(script, /pack-audit-quick-start/);
  assert.match(script, /read-only-tool-call/);
  assert.match(script, /pack-voice-quick-start/);
  assert.match(script, /pack-agent-setup-profiles/);
  assert.match(script, /voice-tool-call/);
  assert.match(script, /pack-production-evidence-quick-start/);
  assert.match(script, /renderTunnelReadySummary/);
  assert.match(script, /Remote agent handoff block/);
  assert.match(script, /Required proof before work/);
  assert.match(script, /arcigy\.get_operator_briefing/);
  assert.match(script, /dryRun=true/);
  assert.match(script, /tokenValueReturned=false with repo-only limits/);
  assert.match(script, /connection pack tokenValueReturned=false with repo-only limits and agentSetupProfiles for Claude\/ChatGPT\/Grok/);
  assert.match(script, /remote smoke status=ready with all 35 required remote MCP smoke gates/);
  assert.match(script, /pack-contract-draft-quick-start/);
  assert.match(script, /pack-client-memory-quick-start/);
  assert.match(script, /pack-production-evidence-quick-start/);
  assert.match(script, /production-evidence-tool-call, approval-gate, approval-shape-gate, and secret-redaction/);
  assert.match(script, /Authorization: Bearer <JARVIS_WEB_TOKEN>/);
  assert.match(script, /--no-start-web/);
  assert.match(script, /--generate-token/);
  assert.match(script, /One-time token/);
  assert.match(script, /--help/);
  assert.match(script, /ngrok-skip-browser-warning/);
  assert.match(script, /npx/);
  assert.match(script, /redactSensitiveText/);
  assert.match(script, /process\.stderr\.write\(`\$\{redactSensitiveText\(error\.message\)\}\\n`\)/);
  assert.match(script, /process\.stdout\.write\(`\[\$\{label\}\] \$\{redactSensitiveText\(String\(chunk\)\)\}`\)/);
  assert.match(script, /process\.stderr\.write\(`\[\$\{label\}\] \$\{redactSensitiveText\(String\(chunk\)\)\}`\)/);
  assert.doesNotMatch(script, /API_SECRET_KEY=dummy/);
});
