import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("web tunnel script orchestrates protected Jarvis MCP exposure", () => {
  const packageJson = JSON.parse(readFileSync("package.json", "utf-8")) as { scripts: Record<string, string> };
  const script = readFileSync("scripts/start_web_tunnel.ts", "utf-8");

  assert.equal(packageJson.scripts["web:tunnel"], "node scripts/start_web_tunnel.ts");
  assert.equal(packageJson.scripts["web:tunnel:secure"], "node scripts/start_web_tunnel.ts --generate-token");
  assert.match(script, /JARVIS_WEB_TOKEN/);
  assert.match(script, /randomBytes/);
  assert.match(script, /src\/server\/local-api-server\.ts/);
  assert.match(script, /\/api\/web-bridge-preflight/);
  assert.match(script, /fetchJson<Preflight>\(`\$\{origin\}\/api\/web-bridge-preflight`, token\)/);
  assert.match(script, /headers\.authorization = `Bearer \$\{token\}`/);
  assert.match(script, /\/\.well-known\/arcigy-jarvis\.json/);
  assert.match(script, /External connection pack/);
  assert.match(script, /includeReadiness=true&live=true/);
  assert.match(script, /\/api\/remote-mcp-smoke/);
  assert.match(script, /verifyExternalConnectionPack/);
  assert.match(script, /hasGuardedConnectionPackLimits/);
  assert.match(script, /pathPolicy === "repo-only"/);
  assert.match(script, /writesRequireExplicitToolCall === true/);
  assert.match(script, /bounded JSON/);
  assert.match(script, /body\.auth\?\.header !== "Authorization: Bearer <JARVIS_WEB_TOKEN>"/);
  assert.match(script, /body\.mcpToolCallPattern !== `\$\{publicUrl\}\/api\/mcp\/\{toolName\}`/);
  assert.match(script, /body\.handoff\?\.connectionPackUrl !== `\$\{publicUrl\}\/api\/remote-mcp-pack\?includeReadiness=true&live=true`/);
  assert.match(script, /verifyRemoteMcpSmoke/);
  assert.match(script, /hasReadySmokeCheck/);
  assert.match(script, /"action-manifest", "openapi-schema", "cors-preflight", "pack-limits", "approval-gate", "approval-shape-gate", "secret-redaction"/);
  assert.match(script, /renderTunnelReadySummary/);
  assert.match(script, /Remote agent handoff block/);
  assert.match(script, /Required proof before work/);
  assert.match(script, /arcigy\.get_operator_briefing/);
  assert.match(script, /dryRun=true/);
  assert.match(script, /tokenValueReturned=false with repo-only limits/);
  assert.match(script, /remote smoke status=ready with action-manifest, openapi-schema, cors-preflight, pack-limits, approval-gate, approval-shape-gate, and secret-redaction/);
  assert.match(script, /Authorization: Bearer <JARVIS_WEB_TOKEN>/);
  assert.match(script, /--no-start-web/);
  assert.match(script, /--generate-token/);
  assert.match(script, /One-time token/);
  assert.match(script, /--help/);
  assert.match(script, /ngrok-skip-browser-warning/);
  assert.match(script, /npx/);
  assert.match(script, /redactSensitiveText/);
  assert.match(script, /process\.stderr\.write\(`\$\{redactSensitiveText\(error\.message\)\}\\n`\)/);
  assert.match(script, /process\.stdout\.write\(`\[\$\{label\}\] \$\{redactSensitiveText\(String\(chunk\)\)\}`\)/);
  assert.match(script, /process\.stderr\.write\(`\[\$\{label\}\] \$\{redactSensitiveText\(String\(chunk\)\)\}`\)/);
  assert.doesNotMatch(script, /API_SECRET_KEY=dummy/);
});
