const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("arcigyDesktop", {
  version: () => ipcRenderer.invoke("app:version"),
  openPath: (targetPath) => ipcRenderer.invoke("app:openPath", targetPath),
  coldOutreachBrief: (metrics) => ipcRenderer.invoke("jarvis:coldOutreachBrief", metrics),
  jarvisVoiceEvent: (payload) => ipcRenderer.invoke("jarvis:voiceEvent", payload),
  systemHealth: () => ipcRenderer.invoke("jarvis:systemHealth"),
  runDiagnostics: (payload) => ipcRenderer.invoke("jarvis:runDiagnostics", payload),
  productionReadiness: (payload) => ipcRenderer.invoke("jarvis:productionReadiness", payload),
  notifyOperator: (payload) => ipcRenderer.invoke("jarvis:notifyOperator", payload),
  operatorBriefing: (payload) => ipcRenderer.invoke("jarvis:operatorBriefing", payload),
  webBridgePreflight: () => ipcRenderer.invoke("jarvis:webBridgePreflight"),
  startSecureTunnel: () => ipcRenderer.invoke("jarvis:startSecureTunnel"),
  remoteMcpPack: (payload) => ipcRenderer.invoke("jarvis:remoteMcpPack", payload),
  remoteMcpSmoke: (payload) => ipcRenderer.invoke("jarvis:remoteMcpSmoke", payload),
  getPreparedOutreachReplies: (payload) => ipcRenderer.invoke("jarvis:getPreparedOutreachReplies", payload),
  preparePositiveOutreachReply: (payload) => ipcRenderer.invoke("jarvis:preparePositiveOutreachReply", payload),
  approvePreparedOutreachReply: (payload) => ipcRenderer.invoke("jarvis:approvePreparedOutreachReply", payload),
  sendApprovedOutreachReply: (payload) => ipcRenderer.invoke("jarvis:sendApprovedOutreachReply", payload),
  identifyEmail: (payload) => ipcRenderer.invoke("jarvis:identifyEmail", payload),
  ingestClientMessage: (payload) => ipcRenderer.invoke("jarvis:ingestClientMessage", payload),
  getClientNeedAlerts: (payload) => ipcRenderer.invoke("jarvis:getClientNeedAlerts", payload),
  getAuditEvents: (payload) => ipcRenderer.invoke("jarvis:getAuditEvents", payload),
  generateAiReply: (payload) => ipcRenderer.invoke("jarvis:generateAiReply", payload),
  syncGmailRecentMessages: (payload) => ipcRenderer.invoke("jarvis:syncGmailRecentMessages", payload),
  getSmartleadCampaignStatus: (payload) => ipcRenderer.invoke("jarvis:getSmartleadCampaignStatus", payload),
  getSmartleadOutreachBrief: (payload) => ipcRenderer.invoke("jarvis:getSmartleadOutreachBrief", payload),
  discoverLeads: (payload) => ipcRenderer.invoke("jarvis:discoverLeads", payload),
  appendLeadsToGoogleSheet: (payload) => ipcRenderer.invoke("jarvis:appendLeadsToGoogleSheet", payload),
  draftContractIntake: (payload) => ipcRenderer.invoke("contracts:draftIntake", payload),
  generateContracts: (payload) => ipcRenderer.invoke("contracts:generate", payload),
});
